name: Deploy Retype site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - uses: retypeapp/action-build@latest
